name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Optional: Aktualisierung jede Stunde

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run your script
        id: calculate
        run: |
          echo "Result: $((RANDOM % 100))" > result.txt
          COUNT=$((RANDOM % 100))
          echo "COUNT=$COUNT" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|<!-- COUNT_PLACEHOLDER -->|$COUNT|g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest count"
          git push
